### ISSUE TITLE
Input description

### ISSUE THREAD

**Issue by Dene33** [Atiehmerikh/FABRIK_Full_Body#3]
Hello again! :) It would be really helpful if you could provide the description about the input data.

1. `joints: np.loadtxt("joints_position.txt")` That's clear, **initial 3d coordinates of the joints**;
2. `orientation: np.loadtxt("orientation.txt")` That is **unclear** for me;
3. `target: targetPosition` So it's 3d coordinates in space of what exactly? Is this the point we want to reach? Like the last joint in the hand chain for example? Can we have more than one point? Per every limb for example? Or could we have no targets at all (just joints_positions.txt and that's it)?
4. `target_orientation: targetOrientation` That is **unclear** for me;
5. `length: np.loadtxt("joints_position_fixed.txt")` It seems it's the **output** of FABRIK. During initialization it's the same as default joints_position.txt;
6. `theta: np.loadtxt("joints_constraint.txt")` It's **unclear** for me what denotes that file;
7. `constraint_type: constraint_type` It's the list describing type of constraint, I think I can find information about them in original paper but it would be great to have this information somewhere in README as well;
8. `rotation_angle_limit: rotationAngleLimit` Is it possible to have individual rotation angle limits per joint?

Sorry to bother you with questions I can find answers to in the original paper. But I tried to find `target orientation` description in paper and could not. So it would be really helpful to have input description in README. If you need any help with that, let me know! Thanks.

**Comment by Atiehmerikh** [comment]
Hi
I don't know why this email was mistakenly missed!
I updated the README file I hope your question is answered. Otherwise
please tell me.
Regards
